public enum DocumentType {
    ARTICLE,
    BOOK,
    BOOKLET,
    CONFERENCE,
    INBOOK,
    INCOLLECTION,
    INPROCEEDINGS,
    MANUAL,
    MASTERSTHESIS,
    MISC,
    PHDTHESIS,
    PROCEEDINGS,
    TECHREPORT,
    UNPUBLISHED,
}
